name: DepthAI Launcher CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:

  windows-installer:
    runs-on: windows-latest

    steps:

    # Clones repository without persisting credentials
    # As this local git repository is packed with installer
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        persist-credentials: ''

    # Inno Setup already installed in Windows2019 Image
    # - name: Install Inno Setup
    #   run: .\launcher\windows\inno_setup.ps1

    # Test if Inno Setup is already in PATH
    # - name: Add Inno Setup to PATH
    #   run: echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Build Windows Installer
      run: .\launcher\windows\build.ps1

    - name: Upload Installer artifact
      uses: actions/upload-artifact@v2
      with:
        name: installers
        path: launcher/windows/build/Output/
        retention-days: 5